spring:
  application:
    name: recipemanager
  oracle:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password:
      poolName: HikariPool
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /recipemanager/actuator
      exposure:
        include: health, prometheus, metrics