openapi: 3.0.0
info:
  title: Recipe Management Service
  description: "Recipe Management Service"
  termsOfService: http://swagger.io/terms/
  contact:
    email: sdsomwanshi89@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT
tags:
  - name: Recipe Management
    description: Operations for Recipe Management Service
paths:
  /recipe:
    post:
      summary: Accept and save recipe data
      operationId: saveRecipe
      tags:
        - RecipeData
      parameters:
        - $ref: '#/components/parameters/traceId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InsertRecipeRequest"
        description: User will insert a new recipe
        required: true
      responses:
        '200':
          description: |
            OK
          headers:
            trace-id:
              description: trace ID for this transaction
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InsertRecipeResponse"
components:
  responses:
    BadRequest:
      description: |
        Bad request, see error object for details
      headers:
        trace-id:
          description: trace ID for this transaction
          schema:
            type: string
          example: 2fea0a89-8ebe-40dd-a37e-f58cc1ddb236
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  parameters:
    traceId:
      in: header
      name: trace-id
      description: trace ID for this transaction
      required: true
      schema:
        type: string
  schemas:
    InsertRecipeRequest:
      type: object
      required:
        - recipeName
      properties:
        recipeName:
          type: string
          description: name of the recipe
        recipeType:
          type: string
        recipeQty:
          type: integer
        ingredients:
          type: array
          description: List of ingredients
          items:
            $ref: "#/components/schemas/Ingredient"
        instructions:
          type: array
          description: List of instructions
          items:
            $ref: "#/components/schemas/Instruction"
    InsertRecipeResponse:
      type: object
      properties:
        recipeName:
          type: string
        recipeNature:
          type: string
          enum:
            - VEG
            - NONVEG
        recipeQty:
          type: string
        ingredients:
          type: array
          description: List of ingredients
          items:
            $ref: "#/components/schemas/Ingredient"
        instructions:
          type: array
          description: List of instructions
          items:
            $ref: "#/components/schemas/Instruction"
        createdDate:
          type: string
        updatedDate:
          type: string
    Ingredient:
      type: object
      properties:
        name:
          type: string
    Instruction:
      type: object
      properties:
        instructionName:
          type: string
    Error:
      type: object
      required:
        - status
        - reason
        - message
      properties:
        status:
          type: integer
          format: int32
        reason:
          type: string
        message:
          type: string